defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
  [entryPoints.traefik]
    address = ":8080"

[acme]
  email = "janos@pasztor.at"
  storage = "/etc/traefik/acme/acme.json"
  entryPoint = "https"
  onHostRule = true
  onDemand = false
  [acme.httpChallenge]
    entryPoint = "http"

[docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  exposedbydefault = false

[api]
  entryPoint = "traefik"
  dashboard = true
  debug = true

[ping]
  entryPoint = "traefik"

[metrics]
  [metrics.prometheus]
    entryPoint = "traefik"
    buckets = [0.1,0.3,1.2,5.0]