version: 2
defaults: &defaults
  working_directory: /tmp/project
  docker:
  - image: ubuntu:18.04
jobs:
  build:
    <<: *defaults
    steps:
      - run:
          name: Update package list
          command: apt-get -y update
      - run:
          name: Install git
          command: apt-get install -y git
      - checkout
      - add_ssh_keys
      - run:
          name: Install system packages
          command: apt install -y build-essential libgsl-dev graphviz plantuml ruby ruby-dev ruby-bundler ruby-fast-stemmer ruby-posix-spawn ruby-rmagick libmagickwand-dev imagemagick
      - run:
          name: Install dependencies
          command: JEYKLL_ENV=prod bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run:
          name: Build website
          command: JEYKLL_ENV=prod bundle exec jekyll build
      - persist_to_workspace:
          root: /tmp/project
          paths:
            - _site
            - .circleci
  deploy:
    <<: *defaults
    parallelism: 1
    steps:
      - run:
          name: Update packages
          command: apt-get update -y
      - run:
          name: Install tools
          command: apt-get install -y ca-certificates dnsutils rsync openssh-client
      - run:
          name: SSH config
          command: cp .circleci/ssh-config ~/.ssh/config
      - attach_workspace:
          at: /tmp/project
      - run:
          name: Deploy
          command: ./.circleci/deploy.sh
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - deploy:
          context: pasztor.at
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
